In [111]:

%matplotlib inline

import sklearn
from sklearn.feature_selection import SelectKBest




import gc
import datetime as dt


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from collections import defaultdict

plt.style.use('default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

In [112]:
station = pd.read_csv('station.csv', low_memory=False)
trip_test = pd.read_csv('trip_test.csv', low_memory=False)
trip_train = pd.read_csv('trip_train.csv', low_memory=False)
weather = pd.read_csv('weather.csv', low_memory=False)

In [113]:
trip_train = pd.merge(trip_train, station[['id', 'lat', 'long']], left_on='start_station_id', right_on= 'id' ,how='left')
trip_test = pd.merge(trip_test, station[['id', 'lat', 'long']], left_on='start_station_id', right_on= 'id' ,how='left')

In [114]:
trip_train.drop('id_y', axis=1, inplace=True)
trip_train.rename(columns={'id_x' : 'id', 'lat': 'start_station_lat','long': 'start_station_long'}, inplace=True)

trip_test.drop('id_y', axis=1, inplace=True)
trip_test.rename(columns={'id_x' : 'id', 'lat': 'start_station_lat','long': 'start_station_long'}, inplace=True)

In [115]:
trip_train = pd.merge(trip_train, station[['id', 'lat', 'long']], left_on='end_station_id', right_on= 'id' ,how='left')

trip_test = pd.merge(trip_test, station[['id', 'lat', 'long']], left_on='end_station_id', right_on= 'id' ,how='left')

In [116]:
trip_train.drop('id_y', axis=1, inplace=True)
trip_train.rename(columns={'id_x' : 'id', 'lat': 'end_station_lat','long': 'end_station_long'}, inplace=True)

trip_test.drop('id_y', axis=1, inplace=True)
trip_test.rename(columns={'id_x' : 'id', 'lat': 'end_station_lat','long': 'end_station_long'}, inplace=True)

In [117]:
trip_train['start_station_lat'] = trip_train[pd.to_numeric(trip_train.start_station_lat, errors='coerce').notnull()]['start_station_lat']
trip_train['start_station_long'] = trip_train[pd.to_numeric(trip_train.start_station_long, errors='coerce').notnull()]['start_station_long']
trip_train['end_station_lat'] = trip_train[pd.to_numeric(trip_train.end_station_lat, errors='coerce').notnull()]['end_station_lat']
trip_train['end_station_long'] = trip_train[pd.to_numeric(trip_train.end_station_long, errors='coerce').notnull()]['end_station_long']

trip_test['start_station_lat'] = trip_test[pd.to_numeric(trip_test.start_station_lat, errors='coerce').notnull()]['start_station_lat']
trip_test['start_station_long'] = trip_test[pd.to_numeric(trip_test.start_station_long, errors='coerce').notnull()]['start_station_long']
trip_test['end_station_lat'] = trip_test[pd.to_numeric(trip_test.end_station_lat, errors='coerce').notnull()]['end_station_lat']
trip_test['end_station_long'] = trip_test[pd.to_numeric(trip_test.end_station_long, errors='coerce').notnull()]['end_station_long']

In [118]:
trip_test

,id,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code,start_station_lat,start_station_long,end_station_lat,end_station_long
0,504737,10/18/2014 11:25,Embarcadero at Sansome,60,10/18/2014 12:12,Powell at Post (Union Square),71,426,Customer,77009,37.804770,-122.403234,37.788446,-122.408499
1,530846,11/5/2014 13:00,Embarcadero at Folsom,51,11/5/2014 13:09,Broadway St at Battery St,82,454,Subscriber,94132,37.791464,-122.391034,37.798541,-122.400862
2,813140,6/18/2015 17:34,San Francisco Caltrain (Townsend at 4th),70,6/18/2015 17:37,2nd at Townsend,61,370,Subscriber,94107,37.776617,-122.395260,37.780526,-122.390288
3,897674,8/20/2015 7:06,Civic Center BART (7th at Market),72,8/20/2015 7:15,Townsend at 7th,65,451,Subscriber,94582,37.781039,-122.411748,37.771058,-122.402717
4,322830,6/13/2014 8:46,San Francisco Caltrain 2 (330 Townsend),69,6/13/2014 8:57,Embarcadero at Folsom,51,603,Subscriber,95014,37.776600,-122.395470,37.791464,-122.391034
5,487841,10/7/2014 21:41,2nd at Townsend,61,10/7/2014 21:47,Post at Kearny,47,478,Subscriber,94115,37.780526,-122.390288,37.788975,-122.403452
6,677808,3/11/2015 18:09,Market at 10th,67,3/11/2015 18:22,San Francisco Caltrain (Townsend at 4th),70,505,Subscriber,94025,37.776619,-122.417385,37.776617,-122.395260
7,704449,3/30/2015 17:29,Embarcadero at Vallejo,48,3/30/2015 17:35,Steuart at Market,74,356,Subscriber,94536,37.799953,-122.398525,37.794139,-122.394434
8,833587,7/5/2015 11:54,Market at 10th,67,7/5/2015 12:00,Market at 4th,76,401,Subscriber,94102,37.776619,-122.417385,37.786305,-122.404966
9,420411,8/22/2014 13:30,Embarcadero at Vallejo,48,8/22/2014 13:41,5th at Howard,57,363,Subscriber,94114,37.799953,-122.398525,37.781752,-122.405127
10,354777,7/8/2014 14:05,Embarcadero at Bryant,54,7/8/2014 14:15,Davis at Jackson,42,591,Subscriber,94110,37.787152,-122.388013,37.797280,-122.398436
11,17809,9/11/2013 13:17,Civic Center BART (7th at Market),72,9/11/2013 13:20,San Francisco City Hall,58,588,Subscriber,94707,37.781039,-122.411748,37.778650,-122.418235
12,854667,7/20/2015 19:45,2nd at South Park,64,7/20/2015 19:57,Market at Sansome,77,405,Subscriber,94705,37.782259,-122.392738,37.789625,-122.400811
13,673325,3/9/2015 8:47,2nd at Folsom,62,3/9/2015 8:56,Broadway St at Battery St,82,417,Subscriber,94107,37.785299,-122.396236,37.798541,-122.400862
14,729900,4/17/2015 9:28,San Francisco Caltrain 2 (330 Townsend),69,4/17/2015 9:37,5th at Howard,57,472,Customer,95070,37.776600,-122.395470,37.781752,-122.405127
15,4485,8/29/2013 13:16,Commercial at Montgomery,45,8/29/2013 13:34,Market at 10th,67,410,Customer,94117,37.794231,-122.402923,37.776619,-122.417385
16,349394,7/3/2014 8:03,Harry Bridges Plaza (Ferry Building),50,7/3/2014 8:11,2nd at Townsend,61,526,Subscriber,94904,37.795392,-122.394203,37.780526,-122.390288
17,784460,5/28/2015 13:27,Commercial at Montgomery,45,5/28/2015 13:30,Mechanics Plaza (Market at Battery),75,652,Subscriber,94709,37.794231,-122.402923,37.791300,-122.399051
18,908431,8/27/2015 16:24,Embarcadero at Folsom,51,8/27/2015 16:44,South Van Ness at Market,66,562,Subscriber,94103,37.791464,-122.391034,37.774814,-122.418954
19,805578,6/12/2015 19:57,San Francisco Caltrain 2 (330 Townsend),69,6/12/2015 20:01,Townsend at 7th,65,332,Subscriber,94107,37.776600,-122.395470,37.771058,-122.402717
20,609571,1/19/2015 12:51,Market at Sansome,77,1/19/2015 12:57,2nd at South Park,64,593,Subscriber,94588,37.789625,-122.400811,37.782259,-122.392738
21,269385,5/2/2014 10:40,Washington at Kearny,46,5/2/2014 11:25,Washington at Kearny,46,594,Customer,98118,37.795425,-122.404767,37.795425,-122.404767
22,227320,3/26/2014 9:27,San Francisco Caltrain 2 (330 Townsend),69,3/26/2014 9:36,Market at 4th,76,612,Subscriber,94040,37.776600,-122.395470,37.786305,-122.404966
23,658277,2/25/2015 17:38,Powell Street BART,39,2/25/2015 17:43,Market at 10th,67,501,Subscriber,94107,37.783871,-122.408433,37.776619,-122.417385
24,205479,3/7/2014 13:58,Steuart at Market,74,3/7/2014 14:05,Commercial at Montgomery,45,551,Subscriber,94704,37.794139,-122.394434,37.794231,-122.402923
25,429936,8/28/2014 20:09,2nd at Folsom,62,8/28/2014 20:13,Market at Sansome,77,627,Subscriber,94501,37.785299,-122.396236,37.789625,-122.400811
26,176953,2/5/2014 14:26,Broadway St at Battery St,82,2/5/2014 14:51,Civic Center BART (7th at Market),72,338,Customer,94102,37.798541,-122.400862,37.781039,-122.411748
27,64226,10/18/2013 18:35,Yerba Buena Center of the Arts (3rd @ Howard),68,10/18/2013 18:40,San Francisco Caltrain (Townsend at 4th),70,494,Subscriber,94107,37.784878,-122.401014,37.776617,-122.395260
28,489619,10/8/2014 18:36,Market at Sansome,77,10/8/2014 18:39,Yerba Buena Center of the Arts (3rd @ Howard),68,564,Subscriber,94107,37.789625,-122.400811,37.784878,-122.401014
29,831189,7/2/2015 8:14,Embarcadero at Sansome,60,7/2/2015 8:20,Harry Bridges Plaza (Ferry Building),50,374,Subscriber,94111,37.804770,-122.403234,37.795392,-122.394203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119968,60831,10/16/2013 17:13,Market at 10th,67,10/16/2013 17:20,Market at 4th,76,369,Subscriber,94108,37.776619,-122.417385,37.786305,-122.404966
119969,875546,8/4/2015 17:19,Townsend at 7th,65,8/4/2015 17:26,Civic Center BART (7th at Market),72,583,Subscriber,94707,37.771058,-122.402717,37.781039,-122.411748
119970,126578,12/16/2013 7:48,Market at Sansome,77,12/16/2013 7:53,2nd at South Park,64,627,Subscriber,94611,37.789625,-122.400811,37.782259,-122.392738
119971,244611,4/11/2014 8:22,Market at Sansome,77,4/11/2014 8:27,2nd at South Park,64,353,Subscriber,94606,37.789625,-122.400811,37.782259,-122.392738
119972,110019,11/27/2013 17:14,Steuart at Market,74,11/27/2013 17:28,Market at 10th,67,437,Subscriber,94103,37.794139,-122.394434,37.776619,-122.417385
119973,114911,12/4/2013 10:54,Commercial at Montgomery,45,12/4/2013 11:08,Market at 10th,67,260,Subscriber,94133,37.794231,-122.402923,37.776619,-122.417385
119974,649284,2/18/2015 19:45,Market at 4th,76,2/18/2015 19:53,Market at 10th,67,531,Subscriber,94103,37.786305,-122.404966,37.776619,-122.417385
119975,719648,4/10/2015 7:46,Ryland Park,84,4/10/2015 7:54,San Jose Diridon Caltrain Station,2,90,Subscriber,95110,37.342725,-121.895617,37.329732,-121.901782
119976,536952,11/10/2014 6:47,Ryland Park,84,11/10/2014 6:56,San Jose Civic Center,3,161,Subscriber,5112,37.342725,-121.895617,37.330698,-121.888979
119977,579153,12/17/2014 16:42,2nd at Folsom,62,12/17/2014 16:45,Market at Sansome,77,390,Subscriber,94582,37.785299,-122.396236,37.789625,-122.400811
119978,619244,1/26/2015 18:32,Clay at Battery,41,1/26/2015 18:34,Clay at Battery,41,354,Subscriber,94403,37.795001,-122.399970,37.795001,-122.399970
119979,277802,5/9/2014 8:46,San Francisco Caltrain 2 (330 Townsend),69,5/9/2014 8:52,Yerba Buena Center of the Arts (3rd @ Howard),68,417,Subscriber,94087,37.776600,-122.395470,37.784878,-122.401014
119980,572524,12/10/2014 7:06,San Francisco Caltrain (Townsend at 4th),70,12/10/2014 7:16,Temporary Transbay Terminal (Howard at Beale),55,651,Subscriber,94107,37.776617,-122.395260,37.789756,-122.394643
119981,273279,5/6/2014 8:39,San Antonio Caltrain Station,29,5/6/2014 8:43,San Antonio Shopping Center,31,703,Subscriber,94070,37.406940,-122.106758,37.400443,-122.108338
119982,438379,9/4/2014 15:04,Clay at Battery,41,9/4/2014 15:09,Broadway St at Battery St,82,376,Subscriber,94107,37.795001,-122.399970,37.798541,-122.400862
119983,322903,6/13/2014 9:06,South Van Ness at Market,66,6/13/2014 9:21,2nd at South Park,64,33,Subscriber,94103,37.774814,-122.418954,37.782259,-122.392738
119984,226880,3/25/2014 17:59,Steuart at Market,74,3/25/2014 18:09,Grant Avenue at Columbus Avenue,73,259,Subscriber,94118,37.794139,-122.394434,37.798522,-122.407245
119985,34690,9/25/2013 14:27,Embarcadero at Bryant,54,9/25/2013 14:35,San Francisco Caltrain (Townsend at 4th),70,620,Subscriber,95129,37.787152,-122.388013,37.776617,-122.395260
119986,581506,12/19/2014 17:41,Broadway St at Battery St,82,12/19/2014 17:45,Steuart at Market,74,572,Subscriber,94610,37.798541,-122.400862,37.794139,-122.394434
119987,365644,7/16/2014 7:46,Market at 10th,67,7/16/2014 7:53,Market at 4th,76,601,Subscriber,94107,37.776619,-122.417385,37.786305,-122.404966
119988,18373,9/11/2013 20:27,Townsend at 7th,65,9/11/2013 20:31,San Francisco Caltrain (Townsend at 4th),70,549,Subscriber,94158,37.771058,-122.402717,37.776617,-122.395260
119989,646921,2/17/2015 12:59,Mechanics Plaza (Market at Battery),75,2/17/2015 13:16,Embarcadero at Bryant,54,335,Subscriber,94105,37.791300,-122.399051,37.787152,-122.388013
119990,835970,7/7/2015 9:54,San Francisco Caltrain 2 (330 Townsend),69,7/7/2015 9:59,5th at Howard,57,391,Subscriber,94002,37.776600,-122.395470,37.781752,-122.405127
119991,100540,11/18/2013 18:41,Harry Bridges Plaza (Ferry Building),50,11/18/2013 18:48,Embarcadero at Sansome,60,492,Customer,94133,37.795392,-122.394203,37.804770,-122.403234
119992,503083,10/17/2014 8:06,San Francisco Caltrain 2 (330 Townsend),69,10/17/2014 8:19,Temporary Transbay Terminal (Howard at Beale),55,265,Subscriber,92084,37.776600,-122.395470,37.789756,-122.394643
119993,274799,5/7/2014 8:11,South Van Ness at Market,66,5/7/2014 8:15,Golden Gate at Polk,59,493,Subscriber,94117,37.774814,-122.418954,37.781332,-122.418603
119994,464786,9/22/2014 19:38,San Francisco Caltrain 2 (330 Townsend),69,9/22/2014 19:45,5th at Howard,57,659,Subscriber,94107,37.776600,-122.395470,37.781752,-122.405127
119995,172825,1/31/2014 19:03,Harry Bridges Plaza (Ferry Building),50,1/31/2014 19:56,Harry Bridges Plaza (Ferry Building),50,559,Subscriber,94102,37.795392,-122.394203,37.795392,-122.394203
119996,641204,2/12/2015 9:25,San Jose Diridon Caltrain Station,2,2/12/2015 9:29,Santa Clara at Almaden,4,42,Subscriber,94025,37.329732,-121.901782,37.333988,-121.894902
119997,893371,8/17/2015 17:06,Mechanics Plaza (Market at Battery),75,8/17/2015 17:17,San Francisco Caltrain 2 (330 Townsend),69,288,Subscriber,94070,37.791300,-122.399051,37.776600,-122.395470

In [119]:
from math import radians, cos, sin, asin, sqrt

#distancia entre dos estaciones 
def distanciaEntreEstaciones(long1, lat1, long2, lat2):
    long1, lat1, long2, lat2 = map(radians, [long1, lat1, long2, lat2])
    dLong = long2 - long1 
    dLat = lat2 - lat1 
    a = sin(dLat/2)**2 + cos(lat1) * cos(lat2) * sin(dLong/2)**2
    c = 2 * asin(sqrt(a)) 
    km = 6367 * c
    return km 

distanciaTrain = trip_train.apply(lambda x: distanciaEntreEstaciones(x[11], x[12], x[13], x[14]), axis = 1)
trip_train['distancia_entre_estaciones'] = distanciaTrain

distanciaTest = trip_test.apply(lambda x: distanciaEntreEstaciones(x[10], x[11], x[12], x[13]), axis = 1)
trip_test['distancia_entre_estaciones'] = distanciaTest

In [120]:
del trip_train['start_station_lat']
del trip_train['start_station_long']
del trip_train['end_station_lat']
del trip_train['end_station_long']

del trip_test['start_station_lat']
del trip_test['start_station_long']
del trip_test['end_station_lat']
del trip_test['end_station_long']

In [121]:
fechasStart = trip_train['start_date'].map(lambda x: (x.split(' ')[0]))
trip_train['startDate'] =  fechasStart
fechasEnd = trip_train['end_date'].map(lambda x: (x.split(' ')[0]))
trip_train['endDate'] =  fechasEnd

fechasStartTest = trip_test['start_date'].map(lambda x: (x.split(' ')[0]))
trip_test['startDate'] =  fechasStartTest
fechasEndTest = trip_test['end_date'].map(lambda x: (x.split(' ')[0]))
trip_test['endDate'] =  fechasEndTest

In [122]:
#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_train['start_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 
trip_train['startDate_weekday'] = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%A"))

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_train['end_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 
trip_train['endDate_weekday'] = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%A"))

In [123]:
#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_test['start_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 
trip_test['startDate_weekday'] = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%A"))

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_test['end_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 
trip_test['endDate_weekday'] = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%A"))

In [124]:
#separamos en dos campos nuevos. fecha en formato yyyymmdd y hora del dia en minutos
fechasStart = trip_train['start_date'].map(lambda x: (int(dt.datetime.strptime(x.split(' ')[0], "%m/%d/%Y").strftime("%Y%m%d"))))
horasStart = trip_train['start_date'].map(lambda x: (x.split(' ')[1]))
horasStart = horasStart.map(lambda x: (int(x.split(':')[0]) * 60 *60+ int(x.split(':')[1])*60))

fechasEnd = trip_train['end_date'].map(lambda x: (int(dt.datetime.strptime(x.split(' ')[0], "%m/%d/%Y").strftime("%Y%m%d"))))
horasEnd = trip_train['end_date'].map(lambda x: (x.split(' ')[1]))
horasEnd = horasEnd.map(lambda x: (int(x.split(':')[0]) * 60 *60+ int(x.split(':')[1])*60))

In [125]:
#separamos en dos campos nuevos. fecha en formato yyyymmdd y hora del dia en minutos
fechasStartTest = trip_test['start_date'].map(lambda x: (int(dt.datetime.strptime(x.split(' ')[0], "%m/%d/%Y").strftime("%Y%m%d"))))
horasStartTest = trip_test['start_date'].map(lambda x: (x.split(' ')[1]))
horasStartTest = horasStartTest.map(lambda x: (int(x.split(':')[0]) * 60 *60+ int(x.split(':')[1])*60))

fechasEndTest = trip_test['end_date'].map(lambda x: (int(dt.datetime.strptime(x.split(' ')[0], "%m/%d/%Y").strftime("%Y%m%d"))))
horasEndTest = trip_test['end_date'].map(lambda x: (x.split(' ')[1]))
horasEndTest = horasEndTest.map(lambda x: (int(x.split(':')[0]) * 60 *60+ int(x.split(':')[1])*60))

In [126]:
#ver dia y noche como afecta

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_train['start_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

horas = trip_train['start_date'].map(lambda x:x.split('/')[2].split(' ')[1].split(':')[0])
#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 

fechas = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%m"))

i = 0
deNoche = [0] * fechas.size
for line in fechas:
    if(((int(line) < 4) & (int(line) > 0)) | ((int(line) > 9)&(int(line) < 13))):
        if((int(horas[i]) <18) & (int(horas[i]) > 7)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    else:
        if((int(horas[i]) <20) & (int(horas[i]) > 6)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    i = i + 1 
        
trip_train['startDate_deNoche'] = deNoche

#ver dia y noche como afecta

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_train['end_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

horas = trip_train['end_date'].map(lambda x:x.split('/')[2].split(' ')[1].split(':')[0])
#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 

fechas = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%m"))

i = 0
deNoche = [0] * fechas.size
for line in fechas:
    if(((int(line) < 4) & (int(line) > 0)) | ((int(line) > 9)&(int(line) < 13))):
        if((int(horas[i]) <18) & (int(horas[i]) > 7)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    else:
        if((int(horas[i]) <20) & (int(horas[i]) > 6)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    i = i + 1 
        
trip_train['endDate_deNoche'] = deNoche

In [127]:
#ver dia y noche como afecta

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_test['start_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

horas = trip_test['start_date'].map(lambda x:x.split('/')[2].split(' ')[1].split(':')[0])
#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 

fechas = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%m"))

i = 0
deNoche = [0] * fechas.size
for line in fechas:
    if(((int(line) < 4) & (int(line) > 0)) | ((int(line) > 9)&(int(line) < 13))):
        if((int(horas[i]) <18) & (int(horas[i]) > 7)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    else:
        if((int(horas[i]) <20) & (int(horas[i]) > 6)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    i = i + 1 
        
trip_test['startDate_deNoche'] = deNoche

#ver dia y noche como afecta

#separamos la fecha por / y eliminamos todo lo q hay mas a la derecha del espacio despues del año
fechas = trip_test['end_date'].map(lambda x: (x.split('/')[0], x.split('/')[1], x.split('/')[2].split(' ')[0]))

horas = trip_test['end_date'].map(lambda x:x.split('/')[2].split(' ')[1].split(':')[0])
#convertimos cada tupla de año mes dia a dia de semana ylo guardamos en un nuevo campo 

fechas = fechas.map(lambda x: dt.date(int(x[2]),int(x[0]),int(x[1])).strftime("%m"))

i = 0
deNoche = [0] * fechas.size
for line in fechas:
    if(((int(line) < 4) & (int(line) > 0)) | ((int(line) > 9)&(int(line) < 13))):
        if((int(horas[i]) <18) & (int(horas[i]) > 7)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    else:
        if((int(horas[i]) <20) & (int(horas[i]) > 6)):
            deNoche[i] = 0
        else:
            deNoche[i] = 1
    i = i + 1 
        
trip_test['endDate_deNoche'] = deNoche

In [128]:
weather['zip_code'] = weather['zip_code'].apply(str)

In [129]:
trip_train = trip_train.merge(weather, left_on=['startDate', 'zip_code'], right_on= ['date', 'zip_code'] ,how='left')
trip_test = trip_test.merge(weather, left_on=['startDate', 'zip_code'], right_on= ['date', 'zip_code'] ,how='left')

In [130]:
del trip_train['endDate']
del trip_train['startDate']
del trip_train['id']
del trip_train['start_station_name']
del trip_train['end_station_name']
del trip_train['start_date']
del trip_train['end_date']
del trip_train['date']
del trip_train['zip_code']

del trip_test['endDate']
del trip_test['startDate']
del trip_test['id']
del trip_test['start_station_name']
del trip_test['end_station_name']
del trip_test['start_date']
del trip_test['end_date']
del trip_test['date']
del trip_test['zip_code']

In [131]:
trip_train['start_date'] = fechasStart
trip_train['end_date'] = fechasEnd
trip_train['start_hour'] = horasStart
trip_train['end_hour'] = horasEnd

trip_test['start_date'] = fechasStartTest
trip_test['end_date'] = fechasEndTest
trip_test['start_hour'] = horasStartTest
trip_test['end_hour'] = horasEndTest

In [132]:
#convertimos subscription_type a 1 y 0 
trip_train['duration'] = trip_train[pd.to_numeric(trip_train.duration, errors='coerce').notnull()]['duration']
subscription_type = trip_train['subscription_type'].map(lambda x: 1 if x == 'Subscriber' else 0)
trip_train['subscription_type'] = subscription_type
trip_train.head()

,duration,start_station_id,end_station_id,bike_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,...,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,start_date,end_date,start_hour,end_hour
0,396,50,60,187,1,1.148453,Thursday,Thursday,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,20150827,20150827,30960,31380
1,636,67,46,417,1,1.794651,Monday,Monday,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,20140728,20140728,79560,80220
2,334,77,62,281,1,0.569924,Monday,Monday,0,0,...,10.0,25.0,0,1.0,NaN,305.0,20140609,20140609,31320,31620
3,666,69,55,634,1,0.788625,Monday,Monday,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,20150126,20150126,60900,61620
4,318,67,39,607,1,1.084530,Saturday,Saturday,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,20150829,20150829,54540,54840

In [133]:
subscription_type = trip_test['subscription_type'].map(lambda x: 1 if x == 'Subscriber' else 0)
trip_test['subscription_type'] = subscription_type
trip_test.head()

,start_station_id,end_station_id,bike_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,max_temperature_f,...,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,start_date,end_date,start_hour,end_hour
0,60,71,426,0,1.134631,Saturday,Saturday,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20141018,20141018,41100,43920
1,51,82,454,1,1.170596,Wednesday,Wednesday,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20141105,20141105,46800,47340
2,70,61,370,1,0.599521,Thursday,Thursday,0,0,66.0,...,10.0,23.0,0,3.0,NaN,286.0,20150618,20150618,63240,63420
3,72,65,451,1,1.166403,Thursday,Thursday,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20150820,20150820,25560,26100
4,69,51,603,1,1.012936,Friday,Friday,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20140613,20140613,31560,32220

In [134]:
trip_train['events'].value_counts()

Rain                 8640
Fog                  5415
Fog-Rain              955
Rain-Thunderstorm     176
rain                   38
Name: events, dtype: int64

In [135]:
trip_train['precipitation_inches'] = trip_train['precipitation_inches'].map(lambda x: 0.01 if x == 'T' else x)
trip_test['precipitation_inches'] = trip_test['precipitation_inches'].map(lambda x: 0.01 if x == 'T' else x)

In [136]:
#convertimos las clases de la columna events
events = trip_train['events'].map(lambda x: 0 if ((x == 'rain') or (x == 'Rain')) else 1 if x == 'Fog' else 2 if x == 'Fog-Rain' else 3 if x == 'Rain-Thunderstorm' else 4)
trip_train['events'] = events
trip_train.head()

,duration,start_station_id,end_station_id,bike_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,...,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,start_date,end_date,start_hour,end_hour
0,396,50,60,187,1,1.148453,Thursday,Thursday,0,0,...,NaN,NaN,NaN,NaN,4,NaN,20150827,20150827,30960,31380
1,636,67,46,417,1,1.794651,Monday,Monday,1,1,...,NaN,NaN,NaN,NaN,4,NaN,20140728,20140728,79560,80220
2,334,77,62,281,1,0.569924,Monday,Monday,0,0,...,10.0,25.0,0,1.0,4,305.0,20140609,20140609,31320,31620
3,666,69,55,634,1,0.788625,Monday,Monday,0,0,...,NaN,NaN,NaN,NaN,4,NaN,20150126,20150126,60900,61620
4,318,67,39,607,1,1.084530,Saturday,Saturday,0,0,...,NaN,NaN,NaN,NaN,4,NaN,20150829,20150829,54540,54840

In [137]:
events = trip_test['events'].map(lambda x: 0 if ((x == 'rain') or (x == 'Rain')) else 1 if x == 'Fog' else 2 if x == 'Fog-Rain' else 3 if x == 'Rain-Thunderstorm' else 4)
trip_test['events'] = events
trip_test.head()

,start_station_id,end_station_id,bike_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,max_temperature_f,...,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,start_date,end_date,start_hour,end_hour
0,60,71,426,0,1.134631,Saturday,Saturday,0,0,NaN,...,NaN,NaN,NaN,NaN,4,NaN,20141018,20141018,41100,43920
1,51,82,454,1,1.170596,Wednesday,Wednesday,0,0,NaN,...,NaN,NaN,NaN,NaN,4,NaN,20141105,20141105,46800,47340
2,70,61,370,1,0.599521,Thursday,Thursday,0,0,66.0,...,10.0,23.0,0,3.0,4,286.0,20150618,20150618,63240,63420
3,72,65,451,1,1.166403,Thursday,Thursday,0,0,NaN,...,NaN,NaN,NaN,NaN,4,NaN,20150820,20150820,25560,26100
4,69,51,603,1,1.012936,Friday,Friday,0,0,NaN,...,NaN,NaN,NaN,NaN,4,NaN,20140613,20140613,31560,32220

In [138]:
#convertimos las clases de los dias de semana
startDays = trip_train['startDate_weekday'].map(lambda x: 0 if x == 'Monday' else 1 if x == 'Thursday' 
                                             else 2 if x == 'Wednesday' else 3 if x == 'Tuesday' else 4 if x == 'Friday'
                                            else 5 if x == 'Saturday' else 6)
trip_train['startDate_weekday'] = startDays

endDays = trip_train['endDate_weekday'].map(lambda x: 0 if x == 'Monday' else 1 if x == 'Thursday' 
                                             else 2 if x == 'Wednesday' else 3 if x == 'Tuesday' else 4 if x == 'Friday'
                                            else 5 if x == 'Saturday' else 6)
trip_train['endDate_weekday'] = endDays
trip_train['startDate_weekday'].value_counts()

3    100410
2     98407
1     97751
0     95118
4     89915
5     36773
6     31587
Name: startDate_weekday, dtype: int64

In [139]:
#convertimos las clases de los dias de semana
startDays = trip_test['startDate_weekday'].map(lambda x: 0 if x == 'Monday' else 1 if x == 'Thursday' 
                                             else 2 if x == 'Wednesday' else 3 if x == 'Tuesday' else 4 if x == 'Friday'
                                            else 5 if x == 'Saturday' else 6)
trip_test['startDate_weekday'] = startDays

endDays = trip_test['endDate_weekday'].map(lambda x: 0 if x == 'Monday' else 1 if x == 'Thursday' 
                                             else 2 if x == 'Wednesday' else 3 if x == 'Tuesday' else 4 if x == 'Friday'
                                            else 5 if x == 'Saturday' else 6)
trip_test['endDate_weekday'] = endDays
trip_test['startDate_weekday'].value_counts()

3    21849
2    21794
1    21338
0    20755
4    19446
5     8012
6     6804
Name: startDate_weekday, dtype: int64

In [140]:
trip_train['endDate_weekday'].value_counts()

3    100425
2     98424
1     97756
0     95166
4     89755
5     36741
6     31694
Name: endDate_weekday, dtype: int64

In [141]:
trip_train['events'].value_counts()

4    534737
0      8678
1      5415
2       955
3       176
Name: events, dtype: int64

In [142]:
weather.columns

Index(['date', 'max_temperature_f', 'mean_temperature_f', 'min_temperature_f',
       'max_dew_point_f', 'mean_dew_point_f', 'min_dew_point_f',
       'max_humidity', 'mean_humidity', 'min_humidity',
       'max_sea_level_pressure_inches', 'mean_sea_level_pressure_inches',
       'min_sea_level_pressure_inches', 'max_visibility_miles',
       'mean_visibility_miles', 'min_visibility_miles', 'max_wind_Speed_mph',
       'mean_wind_speed_mph', 'max_gust_speed_mph', 'precipitation_inches',
       'cloud_cover', 'events', 'wind_dir_degrees', 'zip_code'],
      dtype='object')

In [146]:
del trip_train['bike_id']
del trip_train['mean_temperature_f']
del trip_train['min_temperature_f']
del trip_train['max_dew_point_f']
del trip_train['min_dew_point_f']
del trip_train['mean_dew_point_f']
del trip_train['mean_humidity']
del trip_train['min_humidity']
del trip_train['max_sea_level_pressure_inches']
del trip_train['min_sea_level_pressure_inches']
del trip_train['mean_sea_level_pressure_inches']
del trip_train['wind_dir_degrees']
del trip_train['mean_visibility_miles']
del trip_train['min_visibility_miles']
del trip_train['max_wind_Speed_mph']
del trip_train['max_humidity']

del trip_test['bike_id']
del trip_test['mean_temperature_f']
del trip_test['min_temperature_f']
del trip_test['max_dew_point_f']
del trip_test['min_dew_point_f']
del trip_test['mean_dew_point_f']
del trip_test['mean_humidity']
del trip_test['min_humidity']
del trip_test['max_sea_level_pressure_inches']
del trip_test['min_sea_level_pressure_inches']
del trip_test['mean_sea_level_pressure_inches']
del trip_test['wind_dir_degrees']
del trip_test['mean_visibility_miles']
del trip_test['min_visibility_miles']
del trip_test['max_wind_Speed_mph']
del trip_test['max_humidity']

KeyError: 'bike_id'

In [147]:
trip_train['intervalo'] = trip_train['end_hour'] - trip_train['start_hour']
trip_test['intervalo'] = trip_test['end_hour'] - trip_test['start_hour']

KeyError: 'end_hour'

In [145]:
trip_train = trip_train.drop(['start_date',
       'end_date', 'start_hour', 'end_hour'] ,axis = 1)

trip_test = trip_test.drop(['start_date',
       'end_date', 'start_hour', 'end_hour'] ,axis = 1)

In [33]:
q = trip_train 
test = trip_test
#w = test
q

,duration,start_station_id,end_station_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,max_temperature_f,max_visibility_miles,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,intervalo
0,396,50,60,1,1.148453,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
1,636,67,46,1,1.794651,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,660
2,334,77,62,1,0.569924,0,0,0,0,78.0,10.0,10.0,25.0,0,1.0,4,300
3,666,69,55,1,0.788625,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,720
4,318,67,39,1,1.084530,5,5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,300
5,337,65,70,1,0.892320,1,1,1,1,71.0,10.0,6.0,26.0,0,5.0,4,360
6,394,64,61,1,0.291147,4,4,0,0,77.0,10.0,10.0,24.0,0,4.0,4,360
7,766,71,70,1,1.631116,2,2,0,0,75.0,10.0,5.0,17.0,0,1.0,4,780
8,531,62,70,1,0.528155,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,540
9,267,76,75,0,0.721470,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,240
10,766,70,67,1,2.458643,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,780
11,416,77,72,1,1.318559,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
12,4120,50,51,0,0.422723,5,5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,4080
13,525,69,51,1,1.012936,1,1,0,0,69.0,10.0,7.0,29.0,0,5.0,4,480
14,301,61,70,1,0.599521,0,0,0,0,81.0,10.0,9.0,25.0,0,0.0,4,300
15,311,39,76,0,0.411638,6,6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,300
16,528,56,61,1,1.028551,4,4,0,0,72.0,10.0,9.0,22.0,0,3.0,4,540
17,4675,50,50,0,0.000000,6,6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,4680
18,203,54,51,1,0.422593,6,6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,180
19,916,55,66,1,2.844347,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,900
20,246,64,54,0,0.600444,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,240
21,431,77,64,1,0.998573,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
22,722,63,65,1,1.077465,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,720
23,275,55,45,1,0.957919,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,300
24,560,74,61,1,0.932210,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,540
25,697,33,28,1,2.509240,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,720
26,1595,50,50,0,0.000000,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,1620
27,470,61,50,1,0.986144,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,480
28,372,2,6,1,0.949790,2,2,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,420
29,472,73,77,1,0.889890,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549931,1111,77,50,0,0.810628,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,1140
549932,523,64,56,1,0.766378,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,480
549933,906,60,74,1,1.164889,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,900
549934,600,50,76,1,1.312732,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,600
549935,290,82,75,1,0.475811,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,300
549936,255,69,61,1,0.621474,5,5,0,0,67.0,10.0,13.0,29.0,0,6.0,4,240
549937,933,54,48,0,1.394752,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,900
549938,180,67,72,1,0.679495,2,2,0,0,63.0,10.0,8.0,20.0,0.01,4.0,0,180
549939,478,72,65,1,1.166403,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,480
549940,682,60,47,1,0.940893,6,6,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,720
549941,878,12,14,1,1.799462,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,900
549942,523,67,68,1,1.884558,0,0,1,1,56.0,10.0,11.0,32.0,0,3.0,4,480
549943,266,28,27,1,0.650964,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,240
549944,771,55,70,1,0.785237,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,780
549945,370,67,76,0,1.495797,6,6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,360
549946,462,50,61,1,0.986144,4,4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,480
549947,830,77,70,1,0.990135,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,780
549948,976,46,39,0,0.799647,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,960
549949,659,69,39,1,1.504175,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,660
549950,473,77,72,1,1.318559,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
549951,1098,55,61,1,0.732210,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,1080
549952,394,62,57,1,1.010336,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
549953,1474,41,72,0,1.550615,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,1500
549954,347,47,73,1,0.707748,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,4,300
549955,577,67,70,1,2.458643,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,600
549956,900,60,70,1,1.896097,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,900
549957,832,61,60,1,2.037939,5,5,0,0,66.0,10.0,3.0,14.0,0,1.0,4,840
549958,466,69,57,0,1.116122,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,420
549959,656,71,65,1,1.218653,3,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,660
549960,293,74,60,1,1.164889,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,300

In [34]:
q[q['max_temperature_f'].notnull()]

,duration,start_station_id,end_station_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,max_temperature_f,max_visibility_miles,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,intervalo
2,334,77,62,1,0.569924,0,0,0,0,78.0,10.0,10.0,25.0,0,1.0,4,300
5,337,65,70,1,0.892320,1,1,1,1,71.0,10.0,6.0,26.0,0,5.0,4,360
6,394,64,61,1,0.291147,4,4,0,0,77.0,10.0,10.0,24.0,0,4.0,4,360
7,766,71,70,1,1.631116,2,2,0,0,75.0,10.0,5.0,17.0,0,1.0,4,780
13,525,69,51,1,1.012936,1,1,0,0,69.0,10.0,7.0,29.0,0,5.0,4,480
14,301,61,70,1,0.599521,0,0,0,0,81.0,10.0,9.0,25.0,0,0.0,4,300
16,528,56,61,1,1.028551,4,4,0,0,72.0,10.0,9.0,22.0,0,3.0,4,540
35,192,49,54,1,0.346678,1,1,1,1,71.0,10.0,6.0,26.0,0,5.0,4,180
43,2408,2,2,1,0.000000,4,4,0,0,67.0,10.0,10.0,36.0,0.01,4.0,0,2400
46,488,50,61,1,0.986144,3,3,0,0,62.0,10.0,5.0,20.0,0,7.0,4,480
49,231,69,65,1,0.870308,4,4,1,1,72.0,10.0,8.0,28.0,0,5.0,1,240
71,632,2,11,1,1.827619,2,2,0,0,63.0,10.0,2.0,14.0,0,3.0,4,600
97,207,64,70,1,0.437455,1,1,0,0,59.0,10.0,1.0,7.0,0,0.0,4,240
106,334,59,57,1,1.497731,3,3,0,0,67.0,10.0,11.0,NaN,0,4.0,4,300
108,270,67,39,1,1.084530,5,5,0,0,64.0,10.0,7.0,18.0,0.08,7.0,0,240
123,421,74,61,1,0.932210,1,1,1,0,70.0,10.0,4.0,NaN,0,0.0,4,420
131,711,69,56,1,0.948971,2,2,0,0,65.0,10.0,5.0,17.0,0.02,5.0,0,660
134,532,72,62,1,1.742340,0,0,0,0,61.0,10.0,6.0,28.0,0.1,7.0,0,540
146,984,39,57,1,0.388450,2,2,0,0,66.0,10.0,9.0,25.0,0,5.0,4,960
163,603,70,72,1,1.851057,4,4,0,0,77.0,10.0,9.0,25.0,0,3.0,4,600
175,424,62,70,1,0.528155,0,0,0,0,73.0,10.0,9.0,22.0,0,4.0,4,420
177,150,70,61,1,0.599521,2,2,0,0,73.0,10.0,10.0,28.0,0,5.0,4,120
178,237,62,61,1,0.719462,2,2,1,1,90.0,10.0,6.0,17.0,0,2.0,4,180
185,639,59,69,1,2.586059,2,2,0,0,65.0,10.0,5.0,17.0,0.02,5.0,0,600
191,499,62,65,1,1.112525,0,0,0,0,60.0,10.0,2.0,10.0,0,5.0,4,480
200,166,82,41,1,0.232931,2,2,0,0,77.0,10.0,9.0,26.0,0.01,6.0,0,180
204,413,65,57,1,0.690851,5,5,0,0,70.0,10.0,8.0,23.0,0,3.0,4,420
208,1134,48,54,1,1.394752,1,1,0,0,76.0,10.0,9.0,26.0,0,4.0,4,1080
218,280,72,57,1,0.736984,3,3,0,0,65.0,10.0,13.0,29.0,0,1.0,4,300
225,835,77,65,1,1.125709,2,2,1,1,59.0,10.0,9.0,24.0,0.01,7.0,4,840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549756,1492,60,69,0,1.886208,5,5,0,0,88.0,10.0,8.0,25.0,0,1.0,4,1440
549760,272,59,72,1,0.761963,4,4,0,0,62.0,10.0,6.0,17.0,0.01,5.0,2,240
549779,301,39,69,1,1.504175,2,2,0,0,70.0,10.0,12.0,31.0,0,5.0,4,300
549803,226,28,27,1,0.650964,3,3,0,0,67.0,10.0,11.0,NaN,0,4.0,4,180
549809,657,72,70,1,1.851057,4,4,1,1,60.0,10.0,5.0,18.0,0,1.0,4,660
549815,567,39,56,1,1.356089,3,3,0,0,74.0,10.0,11.0,37.0,0,1.0,4,540
549820,621,69,49,1,0.976642,1,1,1,1,77.0,10.0,8.0,23.0,0,1.0,4,600
549823,476,54,56,0,1.052942,1,1,0,0,69.0,10.0,10.0,25.0,0,3.0,4,480
549827,371,74,54,1,0.825912,6,6,0,0,60.0,10.0,18.0,51.0,0.01,6.0,0,420
549828,521,61,74,1,0.932210,1,1,0,0,67.0,10.0,6.0,20.0,0.01,5.0,0,540
549829,413,68,64,1,0.932797,4,4,1,1,72.0,10.0,13.0,25.0,0,5.0,4,420
549837,620,65,39,1,0.992832,0,0,0,0,80.0,9.0,10.0,24.0,0,1.0,4,600
549840,1871,69,64,1,0.453512,1,1,0,0,63.0,10.0,6.0,35.0,0,7.0,4,1920
549845,1413,31,35,1,6.619025,2,2,0,0,66.0,10.0,7.0,NaN,0,2.0,4,1440
549847,444,47,61,1,1.546927,4,4,0,0,63.0,10.0,8.0,37.0,0,3.0,4,480
549848,468,82,47,1,0.638212,4,4,0,0,63.0,10.0,22.0,40.0,0.91,8.0,0,480
549858,370,54,69,1,1.039840,1,1,0,0,74.0,10.0,7.0,26.0,0,5.0,4,360
549862,541,69,39,1,1.504175,4,4,0,0,71.0,10.0,9.0,21.0,0,4.0,4,540
549886,1039,68,70,1,0.806711,3,3,1,1,65.0,10.0,2.0,31.0,0,7.0,1,1020
549887,479,62,70,1,0.528155,1,1,0,0,52.0,10.0,7.0,23.0,0.64,8.0,0,480
549898,622,61,76,1,1.666992,0,0,0,0,64.0,10.0,7.0,31.0,0,1.0,4,600
549903,324,77,62,1,0.569924,2,2,0,0,61.0,10.0,9.0,28.0,0,6.0,1,300
549906,732,55,65,1,1.429850,0,0,0,0,73.0,10.0,9.0,22.0,0,4.0,4,720
549918,199,65,70,1,0.892320,0,0,0,0,68.0,10.0,16.0,32.0,0,5.0,4,180
549921,509,67,57,1,1.396060,0,0,0,0,65.0,10.0,6.0,17.0,0,5.0,4,540
549923,439,82,54,1,1.580660,4,4,0,0,70.0,10.0,4.0,15.0,0.01,3.0,1,420
549936,255,69,61,1,0.621474,5,5,0,0,67.0,10.0,13.0,29.0,0,6.0,4,240
549938,180,67,72,1,0.679495,2,2,0,0,63.0,10.0,8.0,20.0,0.01,4.0,0,180
549942,523,67,68,1,1.884558,0,0,1,1,56.0,10.0,11.0,32.0,0,3.0,4,480
549957,832,61,60,1,2.037939,5,5,0,0,66.0,10.0,3.0,14.0,0,1.0,4,840

In [35]:
a = q['duration'].mean()
b = q['start_station_id'].mean()
c = q['end_station_id'].mean()
d = q['subscription_type'].mean()
e = q['distancia_entre_estaciones'].mean()
f = q['startDate_weekday'].mean()
g = q['endDate_weekday'].mean()
h = q['startDate_deNoche'].mean()
i = q['endDate_deNoche'].mean()
j = q['max_temperature_f'].mean()
k = q['max_visibility_miles'].mean()
l = q['mean_wind_speed_mph'].mean()
m = q['max_gust_speed_mph'].mean()
#n = q['precipitation_inches'].mean()
o = q['cloud_cover'].mean()
p = q['events'].mean()


#ac = q['mean_temperature_f'].mean()
#ad = q['min_temperature_f'].mean()
#ae = q['max_dew_point_f'].mean()
#af = q['min_dew_point_f'].mean()
#ag = q['mean_dew_point_f'].mean()
#ah = q['mean_humidity'].mean()
#ai = q['min_humidity'].mean()
#aj = q['max_sea_level_pressure_inches'].mean()
#ak = q['min_sea_level_pressure_inches'].mean()
#al = q['mean_sea_level_pressure_inches'].mean()
#am = q['wind_dir_degrees'].mean()
#an = q['mean_visibility_miles'].mean()
#ao = q['min_visibility_miles'].mean()
#ap = q['max_wind_Speed_mph'].mean()
#aq = q['max_humidity'].mean()

In [36]:
q1 = q.dropna(how='all')
q1 = q1.replace([np.inf, -np.inf], np.nan)
#q1 = q.fillna(0)
q1['duration'] = q['duration'].fillna(a)
q1['start_station_id'] = q['start_station_id'].fillna(b)
q1['end_station_id'] = q['end_station_id'].fillna(c)
q1['subscription_type'] = q['subscription_type'].fillna(d)
q1['distancia_entre_estaciones'] = q['distancia_entre_estaciones'].fillna(e)
q1['startDate_weekday'] = q['startDate_weekday'].fillna(f)
q1['endDate_weekday'] = q['endDate_weekday'].fillna(g)
q1['startDate_deNoche'] = q['startDate_deNoche'].fillna(h)
q1['endDate_deNoche'] = q['endDate_deNoche'].fillna(i)
q1['max_temperature_f'] = q['max_temperature_f'].fillna(j)
q1['max_visibility_miles'] = q['max_visibility_miles'].fillna(k)
q1['mean_wind_speed_mph'] = q['mean_wind_speed_mph'].fillna(l)
q1['max_gust_speed_mph'] = q['max_gust_speed_mph'].fillna(m)
q1['precipitation_inches'] = q['precipitation_inches'].fillna(0)
q1['cloud_cover'] = q['cloud_cover'].fillna(o)
q1['events'] = q['events'].fillna(p)
q2 = q1
#q1 = q1.replace(q1.mean(),np.nan)
#w = q.fillna(0)


#q1['mean_temperature_f'] = q['mean_temperature_f'].fillna(ac)
#q1['min_temperature_f']  = q['min_temperature_f'].fillna(ad)
#q1['max_dew_point_f'] = q['max_dew_point_f'].fillna(ae)
#q1['min_dew_point_f'] = q['min_dew_point_f'].fillna(af)
#q1['mean_dew_point_f'] = q['mean_dew_point_f'].fillna(ag)
#q1['mean_humidity'] = q['mean_humidity'].fillna(ah)
#q1['min_humidity'] = q['min_humidity'].fillna(ai)
#q1['max_sea_level_pressure_inches'] =q['max_sea_level_pressure_inches'].fillna(aj)
#q1['min_sea_level_pressure_inches']  = q['min_sea_level_pressure_inches'].fillna(ak)
#q1['mean_sea_level_pressure_inches'] = q['mean_sea_level_pressure_inches'].fillna(al)
#q1['wind_dir_degrees'] = q['wind_dir_degrees'].fillna(am)
#q1['mean_visibility_miles'] = q['mean_visibility_miles'].fillna(an)
#q1['min_visibility_miles']  = q['min_visibility_miles'].fillna(ao)
#q1['max_wind_Speed_mph'] = q['max_wind_Speed_mph'].fillna(ap)
#q1['max_humidity'] = q['max_humidity'].fillna(aq)

In [ ]:
q = test
a = q['duration'].mean()
b = q['start_station_id'].mean()
c = q['end_station_id'].mean()
d = q['subscription_type'].mean()
e = q['distancia_entre_estaciones'].mean()
f = q['startDate_weekday'].mean()
g = q['endDate_weekday'].mean()
h = q['startDate_deNoche'].mean()
i = q['endDate_deNoche'].mean()
j = q['max_temperature_f'].mean()
k = q['max_visibility_miles'].mean()
l = q['mean_wind_speed_mph'].mean()
m = q['max_gust_speed_mph'].mean()
#n = q['precipitation_inches'].mean()
o = q['cloud_cover'].mean()
p = q['events'].mean()

In [ ]:
q1 = q.dropna(how='all')
q1 = q1.replace([np.inf, -np.inf], np.nan)
#q1 = q.fillna(0)
q1['duration'] = q['duration'].fillna(a)
q1['start_station_id'] = q['start_station_id'].fillna(b)
q1['end_station_id'] = q['end_station_id'].fillna(c)
q1['subscription_type'] = q['subscription_type'].fillna(d)
q1['distancia_entre_estaciones'] = q['distancia_entre_estaciones'].fillna(e)
q1['startDate_weekday'] = q['startDate_weekday'].fillna(f)
q1['endDate_weekday'] = q['endDate_weekday'].fillna(g)
q1['startDate_deNoche'] = q['startDate_deNoche'].fillna(h)
q1['endDate_deNoche'] = q['endDate_deNoche'].fillna(i)
q1['max_temperature_f'] = q['max_temperature_f'].fillna(j)
q1['max_visibility_miles'] = q['max_visibility_miles'].fillna(k)
q1['mean_wind_speed_mph'] = q['mean_wind_speed_mph'].fillna(l)
q1['max_gust_speed_mph'] = q['max_gust_speed_mph'].fillna(m)
q1['precipitation_inches'] = q['precipitation_inches'].fillna(0)
q1['cloud_cover'] = q['cloud_cover'].fillna(o)
q1['events'] = q['events'].fillna(p)

test = q1
q1 = q2

In [206]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

q5 = q1
dur = q5['end_hour'] - q5['start_hour']
q5['dur'] = dur
q5['is_true'] = np.random.uniform(0,1,len(trip_train)) <= 0.1
pruebaD, pruebaT = q5[q5['is_true']==True], q5[q5['is_true']==False]
del q5['is_true']
del pruebaD['is_true']
del pruebaT['is_true']
pruebaD_x = pruebaD.drop('duration'
             , axis=1)
pruebaD_y = pruebaD['duration']
    
pruebaT_x = pruebaT.drop('duration'
             , axis=1)
pruebaT_y = pruebaT['duration']

pruebaD_x = preprocessing.normalize(pruebaD_x)
#pruebaT_x = preprocessing.normalize(pruebaT_x)
#numpyMatrix = pruebaD_x.as_matrix().astype(float)
#pruebaD_x = preprocessing.scale(pruebaD_x)
#pruebaT_x = preprocessing.scale(pruebaT_x)

scaler = StandardScaler()
scaler.fit(pruebaD_x) 
pruebaD_x= scaler.transform(pruebaD_x)
#pruebaD_y = scaler.transform(pruebaD_y)

In [168]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from numpy import random
from sklearn.svm import LinearSVR
from sklearn import linear_model
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import make_scorer
import time
#for i in range(50):
print("[INFO] tuning hyperparameters via grid search")
        
params = [
         { 'average' : [False] , 'loss' : ['squared_epsilon_insensitive'],
          'penalty': ['l1', 'l2', 'elasticnet'] ,'learning_rate' : ['invscaling'] , 'eta0' : [1,0.1,0.01,0.0001,0.000000001], 'power_t' : [0.001,0.1,0.45,0.01,0.6],
          'epsilon' : [0.8,0.85,0.1], 'l1_ratio' : [0.4,0.5,0.6,0.8],  'n_iter' : [np.ceil(10**6 / len(pruebaD_x))],
             'alpha' : [1,0.1,0.01,0.001,0.0001,0.0001,0.00001]}  
]
  
#param_dist = {'average' : [True] , 'loss' : ['squared_loss','huber','squared_epsilon_insensitive'],
#              'penalty': ['l1'] ,'learning_rate' : ['optimal', 'invscaling'] , 'eta0' : [ random.uniform(0.0000001, 0.2), random.uniform(0.0000001, 0.2) ,random.uniform(0.0000001, 0.2) ], 'power_t' : [ random.uniform(0.1, 0.6), random.uniform(0.1, 0.6), random.uniform(0.1, 0.6) , random.uniform(0.1, 0.6)],
#             'epsilon' : [random.uniform(0,100), random.uniform(0,100), random.uniform(0,100)], 'l1_ratio' : [random.uniform(0,1),random.uniform(0,1),random.uniform(0,1)], 
#                'alpha' : [random.uniform(0.000001,0.5)]}      
#    
model = linear_model.SGDRegressor()
#grid = RandomizedSearchCV(model, param_distributions=param_dist, n_iter=20)

grid = GridSearchCV(model, params, n_jobs = -1)
start = time.time()
print("[INFO] fitting stage")
grid = grid.fit(pruebaD_x, pruebaD_y)
acc = grid.best_score_

print("[INFO] grid search took {:.2f} seconds".format(time.time() - start))
print("[INFO] grid search accuracy: {:.2f}%".format(acc * 100))
print("[INFO] grid search best parameters: {}".format(grid.best_params_))
 
#prediction = grid.best_estimator_.predict(pruebaT_x)
#score = mean_squared_error(pruebaT_y, prediction)
#print("[INFO] grid search best parameters predictor score: {}".format((1 - abs(score)) * 100))

[INFO] tuning hyperparameters via grid search
[INFO] fitting stage
[INFO] grid search took 2052.62 seconds
[INFO] grid search accuracy: 7.21%
[INFO] grid search best parameters: {'alpha': 1, 'average': False, 'epsilon': 0.8, 'eta0': 0.0001, 'l1_ratio': 0.8, 'learning_rate': 'invscaling', 'loss': 'squared_epsilon_insensitive', 'n_iter': 19.0, 'penalty': 'elasticnet', 'power_t': 0.01}

In [78]:
a = abs(grid.best_estimator_.predict(pruebaD_x))
a[0:20]

array([  358.38686369,   415.63085516,   721.09017981,  1160.08804004,
        4022.26659539,  1291.02542164,    86.54751264,    90.56950698,
        3991.52408146,   583.78615836,   618.75636049,  5819.21590603,
         530.47342908,   538.99846963,   217.02910588,  4655.52704509,
         325.06900221,   431.29681313,  1101.59842594,   890.73148117])

In [ ]:
pruebaD_y[0:20]

In [73]:
sklearn.metrics.mean_absolute_error(a,pruebaD_y)

1178.8633393035411

In [44]:
from sklearn import preprocessing
dur = q1['end_hour'] - q1['start_hour']
q1['dur'] = dur
q5 = q1
q5['is_true'] = np.random.uniform(0,1,len(trip_train)) <= 0.05
pruebaD, pruebaT = q5[q5['is_true']==True], q5[q5['is_true']==False]
del q5['is_true']
del pruebaD['is_true']
del pruebaT['is_true']
pruebaD_x = pruebaD.drop('duration'
             , axis=1)
pruebaD_y = pruebaD['duration']
    
pruebaT_x = pruebaT.drop('duration'
             , axis=1)
pruebaT_y = pruebaT['duration']
pruebaT_y = pruebaT['duration']
pruebaD_x = preprocessing.normalize(pruebaD_x)
#pruebaT_x = preprocessing.normalize(pruebaT_x)
#numpyMatrix = pruebaD_x.as_matrix().astype(float)
#pruebaD_x = preprocessing.scale(numpyMatrix)
#prebaD_x = preprocessing.scale(pruebaD_x)
#pruebaT_x = preprocessing.scale(pruebaT_x)

In [39]:
del q1['mean_wind_speed_mph']
del q1['max_gust_speed_mph']
del q1['precipitation_inches']
del q1['cloud_cover']

In [103]:
q5 = q1

q5

,duration,start_station_id,end_station_id,subscription_type,distancia_entre_estaciones,startDate_weekday,endDate_weekday,startDate_deNoche,endDate_deNoche,max_temperature_f,max_visibility_miles,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,intervalo
0,396,50,60,1,1.148453,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
1,636,67,46,1,1.794651,0,0,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,660
2,334,77,62,1,0.569924,0,0,0,0,78.000000,10.000000,10.000000,25.000000,0,1.000000,4,300
3,666,69,55,1,0.788625,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,720
4,318,67,39,1,1.084530,5,5,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300
5,337,65,70,1,0.892320,1,1,1,1,71.000000,10.000000,6.000000,26.000000,0,5.000000,4,360
6,394,64,61,1,0.291147,4,4,0,0,77.000000,10.000000,10.000000,24.000000,0,4.000000,4,360
7,766,71,70,1,1.631116,2,2,0,0,75.000000,10.000000,5.000000,17.000000,0,1.000000,4,780
8,531,62,70,1,0.528155,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,540
9,267,76,75,0,0.721470,1,1,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,240
10,766,70,67,1,2.458643,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,780
11,416,77,72,1,1.318559,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
12,4120,50,51,0,0.422723,5,5,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,4080
13,525,69,51,1,1.012936,1,1,0,0,69.000000,10.000000,7.000000,29.000000,0,5.000000,4,480
14,301,61,70,1,0.599521,0,0,0,0,81.000000,10.000000,9.000000,25.000000,0,0.000000,4,300
15,311,39,76,0,0.411638,6,6,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300
16,528,56,61,1,1.028551,4,4,0,0,72.000000,10.000000,9.000000,22.000000,0,3.000000,4,540
17,4675,50,50,0,0.000000,6,6,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,4680
18,203,54,51,1,0.422593,6,6,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,180
19,916,55,66,1,2.844347,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,900
20,246,64,54,0,0.600444,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,240
21,431,77,64,1,0.998573,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
22,722,63,65,1,1.077465,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,720
23,275,55,45,1,0.957919,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300
24,560,74,61,1,0.932210,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,540
25,697,33,28,1,2.509240,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,720
26,1595,50,50,0,0.000000,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,1620
27,470,61,50,1,0.986144,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,480
28,372,2,6,1,0.949790,2,2,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
29,472,73,77,1,0.889890,2,2,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549931,1111,77,50,0,0.810628,2,2,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,1140
549932,523,64,56,1,0.766378,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,480
549933,906,60,74,1,1.164889,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,900
549934,600,50,76,1,1.312732,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,600
549935,290,82,75,1,0.475811,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300
549936,255,69,61,1,0.621474,5,5,0,0,67.000000,10.000000,13.000000,29.000000,0,6.000000,4,240
549937,933,54,48,0,1.394752,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,900
549938,180,67,72,1,0.679495,2,2,0,0,63.000000,10.000000,8.000000,20.000000,0.01,4.000000,0,180
549939,478,72,65,1,1.166403,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,480
549940,682,60,47,1,0.940893,6,6,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,720
549941,878,12,14,1,1.799462,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,900
549942,523,67,68,1,1.884558,0,0,1,1,56.000000,10.000000,11.000000,32.000000,0,3.000000,4,480
549943,266,28,27,1,0.650964,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,240
549944,771,55,70,1,0.785237,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,780
549945,370,67,76,0,1.495797,6,6,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,360
549946,462,50,61,1,0.986144,4,4,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,480
549947,830,77,70,1,0.990135,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,780
549948,976,46,39,0,0.799647,1,1,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,960
549949,659,69,39,1,1.504175,0,0,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,660
549950,473,77,72,1,1.318559,2,2,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
549951,1098,55,61,1,0.732210,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,1080
549952,394,62,57,1,1.010336,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
549953,1474,41,72,0,1.550615,0,0,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,1500
549954,347,47,73,1,0.707748,0,0,1,1,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300
549955,577,67,70,1,2.458643,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,600
549956,900,60,70,1,1.896097,2,2,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,900
549957,832,61,60,1,2.037939,5,5,0,0,66.000000,10.000000,3.000000,14.000000,0,1.000000,4,840
549958,466,69,57,0,1.116122,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,420
549959,656,71,65,1,1.218653,3,3,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,660
549960,293,74,60,1,1.164889,1,1,0,0,69.243171,10.104086,7.558569,23.438198,0,3.570244,4,300

In [54]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVR
from sklearn.svm import LinearSVC

from sklearn.svm import SVR
from sklearn import linear_model
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import make_scorer
from sklearn import preprocessing
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import time

num = 1
max_Accuracy = 0
for i in range(num):
    q5 = q1
    train_x = q5.drop('duration', axis = 1)
    train_y = q5['duration']
    train_x = preprocessing.normalize(train_x)
   
    
    scaler = StandardScaler()
    scaler.fit(train_x) 
    train_x= scaler.transform(train_x)
       
    print("[INFO] tuning hyperparameters via grid search")
        
    #params = [
    #     { 'average' : [False] , 'loss' : ['squared_epsilon_insensitive'],
    #      'penalty': ['elasticnet'] ,'learning_rate' : ['invscaling'] , 'eta0' : [0.1,1,10,100,0.0001,0.001,0.00001], 'power_t' : [0.45],
    #      'epsilon' : [0.01,0.4,0.001,0.1,1,10,0.0001,0.00001,0.0000001], 'l1_ratio' : [0.4], 'n_iter' : [15],
    #         'alpha' : [0.0001]}  
    #]
    
    params = [
         { 'C' : [10] , 'epsilon' : [0], 'random_state' : [0], 'loss' : ['squared_epsilon_insensitive' ]}  
    ]
    
    # params = [
    #      { 'C' : [1] , 'gamma' : ['auto']}  
    #  ]
    
    model = LinearSVR(verbose = 2,tol= 0.000001, max_iter = 2000)
    #model = linear_model.SGDRegressor()
    #model = SVR(cache_size = 7000)
    grid = GridSearchCV(model, params, n_jobs = -1, cv = 5)
    start = time.time()
    print("[INFO] fitting stage")

    grid = grid.fit(train_x, train_y)
    acc = grid.best_score_
    
    
    #acc = grid.best_score_
    #accs = grid.score(x1, y1)
    print("[INFO] grid search took {:.2f} seconds".format(time.time() - start))
    # evaluate the best grid searched model on the testing data
    print("[INFO] grid search accuracy: {:.2f}%".format(acc * 100))
    print("[INFO] grid search best parameters: {}".format(grid.best_params_))
    #print (accs)

[INFO] tuning hyperparameters via grid search
[INFO] fitting stage
[LibLinear][INFO] grid search took 724.12 seconds
[INFO] grid search accuracy: 11.09%
[INFO] grid search best parameters: {'C': 10, 'epsilon': 0, 'loss': 'squared_epsilon_insensitive', 'random_state': 0}

M:\Users\Krion\Anaconda3\lib\site-packages\sklearn\svm\base.py:920: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [89]:
prediction = grid.best_estimator_.predict(train_x)
train_y[0:30]

0      396
1      636
2      334
3      666
4      318
5      337
6      394
7      766
8      531
9      267
10     766
11     416
12    4120
13     525
14     301
15     311
16     528
17    4675
18     203
19     916
20     246
21     431
22     722
23     275
24     560
25     697
26    1595
27     470
28     372
29     472
Name: duration, dtype: int64

In [90]:
prediction[0:30]

array([  6.06727077e+03,   8.71700869e+03,   3.50341213e+03,
         9.98094048e+03,   7.19944303e+02,   2.95822204e+03,
         3.17064759e+03,   9.77597911e+03,   7.78090828e+03,
        -6.16199702e+02,   8.60734761e+03,   4.07397889e+03,
         1.46076136e+04,   5.80402161e+03,   4.29424695e+03,
         2.36300856e+03,   7.47333575e+03,   1.47751172e+04,
        -4.78832413e+03,   9.78563090e+03,  -1.20125849e+01,
         5.31998149e+03,   9.36653580e+03,   1.80300490e+03,
         7.03380783e+03,   9.46264936e+03,   1.35221338e+04,
         7.32844813e+03,   8.40513051e+03,   6.48772478e+03])

In [82]:
def grid_scores_to_df(grid_scores):
    rows = list()
    for grid_score in grid_scores:
        for fold, score in enumerate(grid_score.cv_validation_scores):
            row = grid_score.parameters.copy()
            row['fold'] = fold
            row['score'] = score
            rows.append(row)
    df = pd.DataFrame(rows)
    return df

grid.grid_scores_

M:\Users\Krion\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:667: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)

[mean: 0.12352, std: 0.06104, params: {'C': 10, 'epsilon': 0, 'loss': 'epsilon_insensitive', 'random_state': 0}]

In [83]:
grid.best_estimator_.coef_

array([ -1.32122818e+02,  -1.30373950e+02,  -5.57689802e+00,
        -1.42966719e+01,   5.89734345e+01,  -6.13606254e+01,
        -1.01631511e+00,   5.81449636e-01,  -2.48314793e+02,
        -2.01186160e+02,   3.26390211e+00,  -3.57294617e+01,
         8.82128493e-01,  -5.82968027e+00,  -2.22167117e+00,
        -1.18047410e+03])